// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: condominium.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createAssociation = `-- name: CreateAssociation :exec
INSERT INTO association (person_id, condominium_id, unit_id, role, active, start_date, end_date, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAssociationParams struct {
	PersonID      int64
	CondominiumID int64
	UnitID        sql.NullInt64
	Role          string
	Active        bool
	StartDate     time.Time
	EndDate       sql.NullTime
	CreatedAt     time.Time
}

func (q *Queries) CreateAssociation(ctx context.Context, arg CreateAssociationParams) error {
	_, err := q.db.ExecContext(ctx, createAssociation,
		arg.PersonID,
		arg.CondominiumID,
		arg.UnitID,
		arg.Role,
		arg.Active,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
	)
	return err
}

const createCondominium = `-- name: CreateCondominium :one
INSERT INTO condominiums (code, name, phone, email, land_area, street, number, neighborhood, city, state, zip_code, latitude, longitude, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id
`

type CreateCondominiumParams struct {
	Code         string
	Name         string
	Phone        string
	Email        string
	LandArea     sql.NullFloat64
	Street       string
	Number       string
	Neighborhood string
	City         string
	State        string
	ZipCode      string
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateCondominium(ctx context.Context, arg CreateCondominiumParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCondominium,
		arg.Code,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.LandArea,
		arg.Street,
		arg.Number,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.ZipCode,
		arg.Latitude,
		arg.Longitude,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createCondominiumCNPJ = `-- name: CreateCondominiumCNPJ :one
INSERT INTO condominium_cnpjs (condominium_id, cnpj, razao_social, descricao, principal, ativo, data_inicio, data_fim)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateCondominiumCNPJParams struct {
	CondominiumID int64
	Cnpj          string
	RazaoSocial   string
	Descricao     string
	Principal     bool
	Ativo         bool
	DataInicio    sql.NullTime
	DataFim       sql.NullTime
}

func (q *Queries) CreateCondominiumCNPJ(ctx context.Context, arg CreateCondominiumCNPJParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCondominiumCNPJ,
		arg.CondominiumID,
		arg.Cnpj,
		arg.RazaoSocial,
		arg.Descricao,
		arg.Principal,
		arg.Ativo,
		arg.DataInicio,
		arg.DataFim,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const existsByCNPJ = `-- name: ExistsByCNPJ :one
SELECT EXISTS(SELECT 1 FROM condominium_cnpjs WHERE cnpj = $1)
`

func (q *Queries) ExistsByCNPJ(ctx context.Context, cnpj string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByCNPJ, cnpj)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByCode = `-- name: ExistsByCode :one
SELECT EXISTS(SELECT 1 FROM condominiums WHERE code = $1)
`

func (q *Queries) ExistsByCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsByCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findCondominiumIDByCode = `-- name: FindCondominiumIDByCode :one
SELECT id
FROM condominiums
WHERE code = $1
`

func (q *Queries) FindCondominiumIDByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRowContext(ctx, findCondominiumIDByCode, code)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCondominiumByID = `-- name: GetCondominiumByID :one
SELECT id, code, name, phone, email, fee_rule, land_area, built_area_sum, street, number, neighborhood, city, state, zip_code, latitude, longitude, status, created_at, updated_at
FROM condominiums
WHERE id = $1
`

func (q *Queries) GetCondominiumByID(ctx context.Context, id int64) (Condominium, error) {
	row := q.db.QueryRowContext(ctx, getCondominiumByID, id)
	var i Condominium
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.FeeRule,
		&i.LandArea,
		&i.BuiltAreaSum,
		&i.Street,
		&i.Number,
		&i.Neighborhood,
		&i.City,
		&i.State,
		&i.ZipCode,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveManagerAssociation = `-- name: HasActiveManagerAssociation :one
SELECT EXISTS (
    SELECT 1
    FROM association
    WHERE person_id = $1
      AND condominium_id = $2
      AND role = 'manager'
      AND active = TRUE
)
`

type HasActiveManagerAssociationParams struct {
	PersonID      int64
	CondominiumID int64
}

func (q *Queries) HasActiveManagerAssociation(ctx context.Context, arg HasActiveManagerAssociationParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasActiveManagerAssociation, arg.PersonID, arg.CondominiumID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listCondominiumCNPJsByCondominiumID = `-- name: ListCondominiumCNPJsByCondominiumID :many
SELECT id, condominium_id, cnpj, razao_social, descricao, principal, ativo, data_inicio, data_fim, created_at
FROM condominium_cnpjs
WHERE condominium_id = $1
ORDER BY id ASC
`

func (q *Queries) ListCondominiumCNPJsByCondominiumID(ctx context.Context, condominiumID int64) ([]CondominiumCnpj, error) {
	rows, err := q.db.QueryContext(ctx, listCondominiumCNPJsByCondominiumID, condominiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CondominiumCnpj{}
	for rows.Next() {
		var i CondominiumCnpj
		if err := rows.Scan(
			&i.ID,
			&i.CondominiumID,
			&i.Cnpj,
			&i.RazaoSocial,
			&i.Descricao,
			&i.Principal,
			&i.Ativo,
			&i.DataInicio,
			&i.DataFim,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCondominiumsWithCNPJs = `-- name: ListCondominiumsWithCNPJs :many
SELECT c.id, c.code, c.name, c.phone, c.email, c.fee_rule, c.land_area, c.built_area_sum, c.street, c.number, c.neighborhood, c.city, c.state, c.zip_code, c.latitude, c.longitude, c.status, c.created_at, c.updated_at,
       cc.id, cc.condominium_id, cc.cnpj, cc.razao_social, cc.descricao, cc.principal, cc.ativo, cc.data_inicio, cc.data_fim, cc.created_at
FROM condominiums c
LEFT JOIN condominium_cnpjs cc ON cc.condominium_id = c.id
ORDER BY c.id ASC, cc.id ASC
`

type ListCondominiumsWithCNPJsRow struct {
	ID            int64
	Code          string
	Name          string
	Phone         string
	Email         string
	FeeRule       string
	LandArea      sql.NullFloat64
	BuiltAreaSum  float64
	Street        string
	Number        string
	Neighborhood  string
	City          string
	State         string
	ZipCode       string
	Latitude      sql.NullFloat64
	Longitude     sql.NullFloat64
	Status        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ID_2          sql.NullInt64
	CondominiumID sql.NullInt64
	Cnpj          sql.NullString
	RazaoSocial   sql.NullString
	Descricao     sql.NullString
	Principal     sql.NullBool
	Ativo         sql.NullBool
	DataInicio    sql.NullTime
	DataFim       sql.NullTime
	CreatedAt_2   sql.NullTime
}

func (q *Queries) ListCondominiumsWithCNPJs(ctx context.Context) ([]ListCondominiumsWithCNPJsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCondominiumsWithCNPJs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCondominiumsWithCNPJsRow{}
	for rows.Next() {
		var i ListCondominiumsWithCNPJsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.FeeRule,
			&i.LandArea,
			&i.BuiltAreaSum,
			&i.Street,
			&i.Number,
			&i.Neighborhood,
			&i.City,
			&i.State,
			&i.ZipCode,
			&i.Latitude,
			&i.Longitude,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ID_2,
			&i.CondominiumID,
			&i.Cnpj,
			&i.RazaoSocial,
			&i.Descricao,
			&i.Principal,
			&i.Ativo,
			&i.DataInicio,
			&i.DataFim,
			&i.CreatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCondominiumFeeRule = `-- name: UpdateCondominiumFeeRule :exec
UPDATE condominiums
SET fee_rule = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCondominiumFeeRuleParams struct {
	ID      int64
	FeeRule string
}

func (q *Queries) UpdateCondominiumFeeRule(ctx context.Context, arg UpdateCondominiumFeeRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateCondominiumFeeRule, arg.ID, arg.FeeRule)
	return err
}

const updateCondominiumLandArea = `-- name: UpdateCondominiumLandArea :exec
UPDATE condominiums
SET land_area = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCondominiumLandAreaParams struct {
	ID       int64
	LandArea sql.NullFloat64
}

func (q *Queries) UpdateCondominiumLandArea(ctx context.Context, arg UpdateCondominiumLandAreaParams) error {
	_, err := q.db.ExecContext(ctx, updateCondominiumLandArea, arg.ID, arg.LandArea)
	return err
}
