// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: member.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createBond = `-- name: CreateBond :one
INSERT INTO association (person_id, condominium_id, unit_id, role, active, start_date, end_date, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CreateBondParams struct {
	PersonID      int64
	CondominiumID int64
	UnitID        sql.NullInt64
	Role          string
	Active        bool
	StartDate     time.Time
	EndDate       sql.NullTime
	CreatedAt     time.Time
}

func (q *Queries) CreateBond(ctx context.Context, arg CreateBondParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createBond,
		arg.PersonID,
		arg.CondominiumID,
		arg.UnitID,
		arg.Role,
		arg.Active,
		arg.StartDate,
		arg.EndDate,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deactivateBond = `-- name: DeactivateBond :execrows
UPDATE association
SET active = FALSE,
    end_date = $4
WHERE id = $1
  AND condominium_id = $2
  AND unit_id = $3
  AND active = TRUE
`

type DeactivateBondParams struct {
	ID            int64
	CondominiumID int64
	UnitID        sql.NullInt64
	EndDate       sql.NullTime
}

func (q *Queries) DeactivateBond(ctx context.Context, arg DeactivateBondParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deactivateBond,
		arg.ID,
		arg.CondominiumID,
		arg.UnitID,
		arg.EndDate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listMembersByUnitID = `-- name: ListMembersByUnitID :many
SELECT a.id, a.person_id, a.unit_id, u.name, u.email, a.role, a.active, a.start_date, a.end_date, a.created_at
FROM association a
JOIN users u ON u.id = a.person_id
WHERE a.unit_id = $1
ORDER BY a.id ASC
`

type ListMembersByUnitIDRow struct {
	ID        int64
	PersonID  int64
	UnitID    sql.NullInt64
	Name      string
	Email     string
	Role      string
	Active    bool
	StartDate time.Time
	EndDate   sql.NullTime
	CreatedAt time.Time
}

func (q *Queries) ListMembersByUnitID(ctx context.Context, unitID sql.NullInt64) ([]ListMembersByUnitIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listMembersByUnitID, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByUnitIDRow{}
	for rows.Next() {
		var i ListMembersByUnitIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.UnitID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.Active,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
