// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
	"time"
)

type Association struct {
	ID            int64
	PersonID      int64
	CondominiumID int64
	UnitID        sql.NullInt64
	Role          string
	Active        bool
	StartDate     time.Time
	EndDate       sql.NullTime
	CreatedAt     time.Time
}

type Condominium struct {
	ID           int64
	Code         string
	Name         string
	Phone        string
	Email        string
	FeeRule      string
	LandArea     sql.NullFloat64
	BuiltAreaSum float64
	Street       string
	Number       string
	Neighborhood string
	City         string
	State        string
	ZipCode      string
	Latitude     sql.NullFloat64
	Longitude    sql.NullFloat64
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CondominiumCnpj struct {
	ID            int64
	CondominiumID int64
	Cnpj          string
	RazaoSocial   string
	Descricao     string
	Principal     bool
	Ativo         bool
	DataInicio    sql.NullTime
	DataFim       sql.NullTime
	CreatedAt     time.Time
}

type Unit struct {
	ID            int64
	CondominiumID int64
	Code          string
	Identifier    string
	GroupType     sql.NullString
	GroupName     sql.NullString
	Floor         sql.NullString
	Description   sql.NullString
	PrivateArea   sql.NullFloat64
	IdealFraction sql.NullFloat64
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID             int64
	ExternalAuthID sql.NullString
	FirstName      string
	LastName       string
	Name           string
	Email          string
	CriadoEm       time.Time
	AtualizadoEm   time.Time
}
