// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unit.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const clearIdealFractionForActiveUnits = `-- name: ClearIdealFractionForActiveUnits :exec
UPDATE units
SET ideal_fraction = NULL
WHERE condominium_id = $1 AND active = TRUE
`

func (q *Queries) ClearIdealFractionForActiveUnits(ctx context.Context, condominiumID int64) error {
	_, err := q.db.ExecContext(ctx, clearIdealFractionForActiveUnits, condominiumID)
	return err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (condominium_id, code, identifier, group_type, group_name, floor, description, private_area, active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id
`

type CreateUnitParams struct {
	CondominiumID int64
	Code          string
	Identifier    string
	GroupType     sql.NullString
	GroupName     sql.NullString
	Floor         sql.NullString
	Description   sql.NullString
	PrivateArea   sql.NullFloat64
	Active        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.CondominiumID,
		arg.Code,
		arg.Identifier,
		arg.GroupType,
		arg.GroupName,
		arg.Floor,
		arg.Description,
		arg.PrivateArea,
		arg.Active,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const existsUnitByGroupNameAndIdentifier = `-- name: ExistsUnitByGroupNameAndIdentifier :one
SELECT EXISTS(
    SELECT 1
    FROM units
    WHERE condominium_id = $1
      AND COALESCE(group_name, '') = COALESCE($2, '')
      AND identifier = $3
)
`

type ExistsUnitByGroupNameAndIdentifierParams struct {
	CondominiumID int64
	GroupName     sql.NullString
	Identifier    string
}

func (q *Queries) ExistsUnitByGroupNameAndIdentifier(ctx context.Context, arg ExistsUnitByGroupNameAndIdentifierParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsUnitByGroupNameAndIdentifier, arg.CondominiumID, arg.GroupName, arg.Identifier)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCondominiumAreasForUnitCalc = `-- name: GetCondominiumAreasForUnitCalc :one
SELECT land_area, built_area_sum
FROM condominiums
WHERE id = $1
`

type GetCondominiumAreasForUnitCalcRow struct {
	LandArea     sql.NullFloat64
	BuiltAreaSum float64
}

func (q *Queries) GetCondominiumAreasForUnitCalc(ctx context.Context, id int64) (GetCondominiumAreasForUnitCalcRow, error) {
	row := q.db.QueryRowContext(ctx, getCondominiumAreasForUnitCalc, id)
	var i GetCondominiumAreasForUnitCalcRow
	err := row.Scan(&i.LandArea, &i.BuiltAreaSum)
	return i, err
}

const getUnitByGroupNameAndIdentifier = `-- name: GetUnitByGroupNameAndIdentifier :one
SELECT id, condominium_id, code, identifier, group_type, group_name, floor, description, private_area, ideal_fraction, active, created_at, updated_at
FROM units
WHERE condominium_id = $1
  AND COALESCE(group_name, '') = COALESCE($2, '')
  AND identifier = $3
`

type GetUnitByGroupNameAndIdentifierParams struct {
	CondominiumID int64
	GroupName     sql.NullString
	Identifier    string
}

func (q *Queries) GetUnitByGroupNameAndIdentifier(ctx context.Context, arg GetUnitByGroupNameAndIdentifierParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnitByGroupNameAndIdentifier, arg.CondominiumID, arg.GroupName, arg.Identifier)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.Code,
		&i.Identifier,
		&i.GroupType,
		&i.GroupName,
		&i.Floor,
		&i.Description,
		&i.PrivateArea,
		&i.IdealFraction,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitByIDAndCondominiumID = `-- name: GetUnitByIDAndCondominiumID :one
SELECT id, condominium_id, code, identifier, group_type, group_name, floor, description, private_area, ideal_fraction, active, created_at, updated_at
FROM units
WHERE id = $1 AND condominium_id = $2
`

type GetUnitByIDAndCondominiumIDParams struct {
	ID            int64
	CondominiumID int64
}

func (q *Queries) GetUnitByIDAndCondominiumID(ctx context.Context, arg GetUnitByIDAndCondominiumIDParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnitByIDAndCondominiumID, arg.ID, arg.CondominiumID)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CondominiumID,
		&i.Code,
		&i.Identifier,
		&i.GroupType,
		&i.GroupName,
		&i.Floor,
		&i.Description,
		&i.PrivateArea,
		&i.IdealFraction,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUnitsForIdealFractionRecalc = `-- name: ListActiveUnitsForIdealFractionRecalc :many
SELECT id, private_area
FROM units
WHERE condominium_id = $1 AND active = TRUE
ORDER BY id ASC
`

type ListActiveUnitsForIdealFractionRecalcRow struct {
	ID          int64
	PrivateArea sql.NullFloat64
}

func (q *Queries) ListActiveUnitsForIdealFractionRecalc(ctx context.Context, condominiumID int64) ([]ListActiveUnitsForIdealFractionRecalcRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUnitsForIdealFractionRecalc, condominiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveUnitsForIdealFractionRecalcRow{}
	for rows.Next() {
		var i ListActiveUnitsForIdealFractionRecalcRow
		if err := rows.Scan(&i.ID, &i.PrivateArea); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitsByCondominiumID = `-- name: ListUnitsByCondominiumID :many
SELECT id, condominium_id, code, identifier, group_type, group_name, floor, description, private_area, ideal_fraction, active, created_at, updated_at
FROM units
WHERE condominium_id = $1
ORDER BY id ASC
`

func (q *Queries) ListUnitsByCondominiumID(ctx context.Context, condominiumID int64) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnitsByCondominiumID, condominiumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.CondominiumID,
			&i.Code,
			&i.Identifier,
			&i.GroupType,
			&i.GroupName,
			&i.Floor,
			&i.Description,
			&i.PrivateArea,
			&i.IdealFraction,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unitBelongsToCondominium = `-- name: UnitBelongsToCondominium :one
SELECT EXISTS(
    SELECT 1
    FROM units
    WHERE id = $1 AND condominium_id = $2
)
`

type UnitBelongsToCondominiumParams struct {
	ID            int64
	CondominiumID int64
}

func (q *Queries) UnitBelongsToCondominium(ctx context.Context, arg UnitBelongsToCondominiumParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, unitBelongsToCondominium, arg.ID, arg.CondominiumID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCondominiumBuiltAreaSumDelta = `-- name: UpdateCondominiumBuiltAreaSumDelta :exec
UPDATE condominiums
SET built_area_sum = built_area_sum + $2
WHERE id = $1
`

type UpdateCondominiumBuiltAreaSumDeltaParams struct {
	ID           int64
	BuiltAreaSum float64
}

func (q *Queries) UpdateCondominiumBuiltAreaSumDelta(ctx context.Context, arg UpdateCondominiumBuiltAreaSumDeltaParams) error {
	_, err := q.db.ExecContext(ctx, updateCondominiumBuiltAreaSumDelta, arg.ID, arg.BuiltAreaSum)
	return err
}

const updateUnitPrivateArea = `-- name: UpdateUnitPrivateArea :exec
UPDATE units
SET private_area = $2,
    updated_at = $3
WHERE id = $1
`

type UpdateUnitPrivateAreaParams struct {
	ID          int64
	PrivateArea sql.NullFloat64
	UpdatedAt   time.Time
}

func (q *Queries) UpdateUnitPrivateArea(ctx context.Context, arg UpdateUnitPrivateAreaParams) error {
	_, err := q.db.ExecContext(ctx, updateUnitPrivateArea, arg.ID, arg.PrivateArea, arg.UpdatedAt)
	return err
}

const updateUnitIdealFraction = `-- name: UpdateUnitIdealFraction :exec
UPDATE units
SET ideal_fraction = $2
WHERE id = $1
`

type UpdateUnitIdealFractionParams struct {
	ID            int64
	IdealFraction sql.NullFloat64
}

func (q *Queries) UpdateUnitIdealFraction(ctx context.Context, arg UpdateUnitIdealFractionParams) error {
	_, err := q.db.ExecContext(ctx, updateUnitIdealFraction, arg.ID, arg.IdealFraction)
	return err
}
