// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (external_auth_id, first_name, last_name, name, email, criado_em, atualizado_em)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id
`

type CreateUserParams struct {
	ExternalAuthID sql.NullString
	FirstName      string
	LastName       string
	Name           string
	Email          string
	CriadoEm       time.Time
	AtualizadoEm   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ExternalAuthID,
		arg.FirstName,
		arg.LastName,
		arg.Name,
		arg.Email,
		arg.CriadoEm,
		arg.AtualizadoEm,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, external_auth_id, first_name, last_name, name, email, criado_em, atualizado_em
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalAuthID,
		&i.FirstName,
		&i.LastName,
		&i.Name,
		&i.Email,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getUserByExternalAuthID = `-- name: GetUserByExternalAuthID :one
SELECT id, external_auth_id, first_name, last_name, name, email, criado_em, atualizado_em
FROM users
WHERE external_auth_id = $1
`

func (q *Queries) GetUserByExternalAuthID(ctx context.Context, externalAuthID sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByExternalAuthID, externalAuthID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalAuthID,
		&i.FirstName,
		&i.LastName,
		&i.Name,
		&i.Email,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_auth_id, first_name, last_name, name, email, criado_em, atualizado_em
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalAuthID,
		&i.FirstName,
		&i.LastName,
		&i.Name,
		&i.Email,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const updateUserIdentity = `-- name: UpdateUserIdentity :exec
UPDATE users
SET external_auth_id = $2,
    first_name = $3,
    last_name = $4,
    name = $5,
    email = $6,
    atualizado_em = $7
WHERE id = $1
`

type UpdateUserIdentityParams struct {
	ID             int64
	ExternalAuthID sql.NullString
	FirstName      string
	LastName       string
	Name           string
	Email          string
	AtualizadoEm   time.Time
}

func (q *Queries) UpdateUserIdentity(ctx context.Context, arg UpdateUserIdentityParams) error {
	_, err := q.db.ExecContext(ctx, updateUserIdentity,
		arg.ID,
		arg.ExternalAuthID,
		arg.FirstName,
		arg.LastName,
		arg.Name,
		arg.Email,
		arg.AtualizadoEm,
	)
	return err
}
